%% Script_ShakeTableKanaiTajimiFRFTests
% Five-run NAMAZU Kanai-Tajimi base-excitation test targeting the first
% retained hammer-test mode with a conservatively extended 30 Hz band.
%
% Hammer reference from the 100 usable measurements:
%   first mode mean = 15.1415 Hz
%
% This setup intentionally targets only that first mode. The higher hammer
% modes near 43.76, 69.60, and 85.30 Hz require a separately validated
% command rate, motor capability, displacement resolution, and safety
% assessment.

clc;
clearvars;
close all;

%% -------------------- PROJECT PATHS --------------------
scriptPath = mfilename("fullpath");
funTestsFolder = fileparts(scriptPath);
functionsFolder = fileparts(funTestsFolder);
matlabRoot = fileparts(functionsFolder);

addpath(genpath(fullfile(matlabRoot, "Methods")));
addpath(genpath(fullfile(matlabRoot, "Functions")));
addpath(genpath(fullfile(matlabRoot, "Classes")));

outputRoot = fullfile(matlabRoot, "Experiments", ...
    "Shake-Table-FRF-Tests");

%% -------------------- HARDWARE --------------------
numberOfTests = 5;
motorPort = "COM11";
sensorPort = "COM5";
motorBaud = 921600;
sensorBaud = 1000000;
numberOfSensors = 5;
sensorSampleRateHz = 250;
accelerometerRangeG = 8;
analysisDirection = "y";

%% -------------------- HAMMER REFERENCE --------------------
hammerReferenceFrequencyHz = 15.1415;

%% -------------------- KANAI-TAJIMI EXCITATION --------------------
analysisMinimumHz = 5;
analysisMaximumHz = 30;
kanaiTajimiCenterFrequencyHz = hammerReferenceFrequencyHz;
kanaiTajimiDampingRatio = 0.45;

excitationDurationSeconds = 45;
motorCommandRateHz = 200;
spectralComponents = 300;
randomSeed = 1514;
rampSeconds = 3;
extraAcquisitionSeconds = 5;

% The generated displacement is scaled after filtering so its numerically
% differentiated command acceleration does not exceed this value.
targetPeakCommandAccelerationG = 0.2;
maximumCommandDisplacementMm = 0.75;

%% -------------------- ANALYSIS AND OUTPUT --------------------
minimumPeakCoherence = 0.70;
modeMatchToleranceHz = 0.75;
minimumModeOccurrenceFraction = 0.80;
referenceMatchToleranceHz = 1.0;

timestamp = char(datetime("now", "Format", "HH-mm-ss"));
folderName = "ST_26_07_29_" + timestamp + ...
    "_Kanai_Tajimi_15Hz_Center_30Hz_Band_5_Runs";

fprintf("\nKanai-Tajimi validation target: %.4f Hz\n", ...
    hammerReferenceFrequencyHz);
fprintf("Only the first hammer mode is inside the %.1f-%.1f Hz test band.\n", ...
    analysisMinimumHz, analysisMaximumHz);
fprintf("Sensor 1 must remain on the moving base; sensors 2-5 remain unchanged.\n");
fprintf("Motor=%s, sensor rig=%s.\n\n", motorPort, sensorPort);

batch = RunShakeTableFRFTestBatch(numberOfTests, ...
    "MotorPort", motorPort, ...
    "MotorBaud", motorBaud, ...
    "SensorPort", sensorPort, ...
    "SensorBaud", sensorBaud, ...
    "NumSensors", numberOfSensors, ...
    "SensorSampleRate", sensorSampleRateHz, ...
    "AccelerometerRangeG", accelerometerRangeG, ...
    "Direction", analysisDirection, ...
    "ExcitationType", "kanai_tajimi", ...
    "StartFrequencyHz", analysisMinimumHz, ...
    "EndFrequencyHz", analysisMaximumHz, ...
    "KanaiTajimiCenterFrequencyHz", kanaiTajimiCenterFrequencyHz, ...
    "KanaiTajimiDampingRatio", kanaiTajimiDampingRatio, ...
    "ExcitationDurationSeconds", excitationDurationSeconds, ...
    "MotorRateHz", motorCommandRateHz, ...
    "SpectralComponents", spectralComponents, ...
    "RandomSeed", randomSeed, ...
    "TargetPeakCommandAccelerationG", targetPeakCommandAccelerationG, ...
    "MaximumCommandDisplacementMm", maximumCommandDisplacementMm, ...
    "RampSeconds", rampSeconds, ...
    "ExtraAcquisitionSeconds", extraAcquisitionSeconds, ...
    "OutputRoot", outputRoot, ...
    "FolderName", folderName, ...
    "FilePrefix", "ST_FRF_KanaiTajimi_15Hz_Center_30Hz_Band", ...
    "ExperimentPhase", "setup_calibration_kanai_tajimi", ...
    "PromptBeforeUpload", true, ...
    "PromptBeforeEachRun", true, ...
    "MakeLivePlot", true, ...
    "MakeFRFPlots", true, ...
    "SaveFRFPlots", true, ...
    "ClosePlotsAfterRun", true, ...
    "MinimumPeakCoherence", minimumPeakCoherence, ...
    "ModeMatchToleranceHz", modeMatchToleranceHz, ...
    "MinModeOccurrenceFraction", minimumModeOccurrenceFraction, ...
    "ReferenceFrequenciesHz", hammerReferenceFrequencyHz, ...
    "ReferenceMatchToleranceHz", referenceMatchToleranceHz);

fprintf("\nKanai-Tajimi setup/calibration batch complete.\n");
fprintf("Data folder: %s\n", batch.outputFolder);
