%Collect one sample with animation
[T, validationMeanTable, meta] = TestSensorRigAnimation("y", "COM9", 1, 60, ...
    "SampleRate", 500, ...
    "Baud", 1000000, ...
    "AnalysisOptions", {"FMax", 100, ...
                        "FrequencyResolutionHz", 0.1, ...
                        "WindowDurationSeconds", 20, ...
                        "MinPeakDistanceHz", 15});

%Check for sampling ratio

fsActual = 1000 / median(diff(T.t_arduino_ms));
disp(fsActual)

EstimateEigenfrequencyFFT(T)