% Collect one sample with animation.
%
% The ESP32 sensor-rig firmware currently streams at 250 Hz. Keep this value
% aligned with SAMPLE_RATE_HZ in Sensors/sensor_rig_esp32/src/main.cpp.
sampleRateHz = 250;
numSensors = 1;
direction = "y";
fMaxHz = 100;

[T, validationMeanTable, meta] = TestSensorRigAnimation(direction, "COM9", numSensors, 60, ...
    "SampleRate", sampleRateHz, ...
    "Baud", 1000000, ...
    "RunAnalysis", false);

%Check for sampling ratio

fsActual = 1000 / median(diff(T.t_arduino_ms));
disp(fsActual)

fftResults = EstimateEigenfrequencyFFT(T, ...
    "Direction", direction, ...
    "SampleRate", sampleRateHz, ...
    "Sensors", 1:numSensors, ...
    "FMax", fMaxHz, ...
    "FrequencyResolutionHz", 0.1, ...
    "MinPeakDistanceHz", 15);
